// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw62RgT_AdMnVfRMy4cE3rMO0JqiCctuw',
    appId: '1:804847092292:web:c4419230afbd88dfedf211',
    messagingSenderId: '804847092292',
    projectId: 'learning-app-project-6770d',
    authDomain: 'learning-app-project-6770d.firebaseapp.com',
    storageBucket: 'learning-app-project-6770d.appspot.com',
    measurementId: 'G-PPS5XWNETD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEB1blfhnx-6FjGYmddB4w3U3kVTZ-hu8',
    appId: '1:804847092292:android:8c96b9390b33a23aedf211',
    messagingSenderId: '804847092292',
    projectId: 'learning-app-project-6770d',
    storageBucket: 'learning-app-project-6770d.appspot.com',
  );
}
